# Building my own actions workflow
# To check the python installation

on:
  workflow_dispatch:
  
jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m build
          find ./dist/*.whl | xargs pip install
          python simple_test.py
      - name: Configure Git
        run: |
          git config --global user.email "jose_antoniotv@hotmail.com"
          git config --global user.name "jatolentino"
      - name: Commit and push wheel
        run: |
          pwd
          ls
          ls ./dist
          git add -f ./dist/*.whl
          git commit -m 'pushing new wheel'
          git push origin master
      - run: echo "This job's status is ${{ job.status }}."
